### ISSUE TITLE
RSVP count

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#132]

**Comment by Dirklectisch** [comment]
Is this just RSVP-ing on resources? If so this is easy for me to implement using the mod_activity build for Stuk van het Jaar voting.

**Comment by ddeboer** [comment]
> RSVP-ing on resources?

Yes.

Where can I find this mod_ginger_activity? Let’s quickly discuss its scope (I’d like to see a readme) and whether events & RSVPs for events fit into that.

**Comment by Dirklectisch** [comment]
It might make more sense to just solve this using regular edges. That being said mod_ginger_activity doesn't prescribe the semantics of what an activity is, so it might just as well be an RSVP. The templates for that should probably just reside in base though.

**Comment by ddeboer** [comment]
Yes, I’d prefer regular edges. @fredpook What about you?
