### ISSUE TITLE
Friendly 'down' screen

### ISSUE THREAD

**Issue by eminetuzkapan** [driebit/ginger#142]
Instead of Zotonic login screen a more friendly screen when a site is down is preferred.

It should contain a short message like: 

"We are experiencing technical problems but we are working on it! 
Please contact us if you keep seeing this screen." 
/
"Er is een technisch probleempje maar er wordt aan gewerkt! 
Neem contact met ons op als dit scherm blijft verschijnen."
- Driebit & Ginger logo
- the hosting e-mail address
- a login link to the zotonic login

**Comment by CyBeRoni** [comment]
See also https://github.com/zotonic/zotonic/issues/1243.

The cases where a 503 is served could be replaced with a nice message, with the login page reserved for when it is specifically requested.
