### ISSUE TITLE
Mod ginger auth disabled, signup page still available

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#143]
After disabling mod ginger auth, you can still acces /signup

**Comment by fredpook** [comment]
Did you try disabling mod_signup ?

**Comment by krista-ramakers** [comment]
Yes I did, but you can still signup.

**Comment by ddeboer** [comment]
Disabled mod_signup [here](http://geheugenvanwest.ginger-test.driebit.net/en/admin/modules), which works fine. Please re-open if you still encounter this issue.
