### ISSUE TITLE
constraint \"fk_activity_log_user_id\" of relation \"activity_log\" does not exist

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#156]

**Comment by Dirklectisch** [comment]
Hmm I think I probably introduced this one last week by accident. Should be easy to fix here:

https://github.com/driebit/ginger/blob/master/modules/mod_ginger_activity/mod_ginger_activity.erl#L36

The constraint should still be dropped if it is there. Otherwise resources won't delete.

**Comment by ddeboer** [comment]
Let’s just assume you were already in the holiday mood. 🌴
