### ISSUE TITLE
Inline PDF view in browser tab is broken

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#157]
PDF preview that automatically opens a new tab after clicking the preview image or the file name at the bottom of the page does not work in Chrome, IE11 and Safari (production/acceptation). The preview only shows in Mozilla. 

According to Fred, two weeks ago everything was still working on production, but at the same time he noticed it did not work on acceptation. He guesses something might have changed in Zotonic considering File header, Content-Type, Content-Disposition.

Kathleen van Wingerden, can you remember if you have seen the previews correctly and how long ago this was?

**Comment by ddeboer** [comment]
Example URL?

**Comment by krista-ramakers** [comment]
https://tudelft.openresearch.net/page/16167/schedule-ri-2016 when clicking the preview image or the document hyperlink (of the pdf file) this happens: https://tudelft.openresearch.net/image/2016/8/8/ri_2016_minor_calendar_q1.pdf

**Comment by ddeboer** [comment]
And downloading the file from the admin?

**Comment by krista-ramakers** [comment]
The preview in browser works after downloading the file from admin.

**Comment by ddeboer** [comment]
> but at the same time he noticed it did not work on acceptation.

Has this been reported as an issue somewhere?

**Comment by fredpook** [comment]
No I didn't report it at that time. I thought it might have to do with mime type settings on acceptatie

**Comment by fredpook** [comment]
If not possible to fix the pdf view in a new tab, we could try the html5 embed pdf viewer like

<embed width="600" height="450" src="mypdf.pdf" type="application/pdf"></embed>

to display the pdf right in the page. 

@danny is this the best way to embed pdf and can you try it in templates/media/media.document.tpl
of the surf project?

**Comment by ddeboer** [comment]
Found the culprit: removing [this line](https://github.com/zotonic/zotonic/blob/0.x/modules/mod_base/controllers/controller_file.erl#L133) fixes the problem. Still investigating.

**Comment by Devenwel** [comment]
I did a quick and dirty test with opening a lightbox with the pdf in it:

![image](https://cloud.githubusercontent.com/assets/8114052/17555584/5834e48c-5f10-11e6-947e-d88bbdfd91ae.png)

Continue with this or wait for David's fix?

**Comment by fredpook** [comment]
@Devenwel I think that fix is not so dirty but a nice solution for surf. Can you put it there so @krista-ramakers can test it?

**Comment by ddeboer** [comment]
I’ll fix the more general problem (inline media not working), which also occurs on other sites, in Zotonic.

**Comment by ddeboer** [comment]
Fixed in Zotonic: https://github.com/zotonic/zotonic/pull/1379.

**Comment by ddeboer** [comment]
Fixed in Zotonic 0.19.2.
