### ISSUE TITLE
Directly download attachments

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#160]
By default, Zotonic shows a media page for attachments such as PDF files or other downloads. Some clients, however, prefer not to have the media page. Instead, they prefer the links to attachments to go directly to the PDF etc. files.

Is this functionality relevant for a larger group of clients?

**Comment by DorienD** [comment]
I think allot of our clients have this wish, but still there is a small group thats prefers pages over direct downloads. It is easy to add a dispatch to a site that needs it.

@ddeboer What would happen if we put that dispatch in ginger base, would it be easy to overwrite on a particular website?

**Comment by DorienD** [comment]
ping @ddeboer

**Comment by fredpook** [comment]
This is about document links in body text, right? As is specified in #213 ?

**Comment by fredpook** [comment]
Currently it works pretty good: Adding a pdf in the body tekst creates the preview image and this links to a direct download (not a media page)
