### ISSUE TITLE
Default meta description (SEO)

### ISSUE THREAD

**Issue by eminetuzkapan** [driebit/ginger#161]
Use part of summary or body (if summary isn't provided) as meta description for search engine optimization.

**Comment by ddeboer** [comment]
Zotonic does this [by default](https://github.com/zotonic/zotonic/blob/master/modules/mod_seo/templates/_html_head.tpl#L24). @DorienD Are we overriding this behaviour somewhere? If not, this should be fixed in Zotonic (not Ginger).

**Comment by DorienD** [comment]
Oh i see, we use our own and the ones from zotonic. I have removed the ones we put in the ginger base, see commit 576649a

**Comment by ddeboer** [comment]
Cool. Does that solve this issue? Do we now see the meta description fallback on pages?

**Comment by DorienD** [comment]
yup
