### ISSUE TITLE
Media properties dialog doesn't appear after clicking image in Mozilla Firefox

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#163]
When you click an image inserted into the body text, the media properties dialog (screenshot attached) should appear (both front end and in Ginger). 
This does not work in Firefox. To access the media properties dialog, you have to click the image and subsequently the 'insert a Zotonic media item' button, in order for the dialog to show.

![edit__add_and_edit_an_article](https://cloud.githubusercontent.com/assets/20204550/17929752/e23349e2-6a02-11e6-9283-740b4554b2fb.png)

Tested on tudelft.openresearch.net and geheugenvanwest.ginger-acceptatie.driebit.net, logged in as admin and user as well.

**Comment by DorienD** [comment]
@krista-ramakers recheck.

**Comment by krista-ramakers** [comment]
@DorienD this problem still occurs!

**Comment by DorienD** [comment]
https://github.com/zotonic/zotonic/issues/1620 Fixed in zotonic
