### ISSUE TITLE
Scrolling in multiple search results on map

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#169]
When you use the search and show the search results on the map, you can't scroll the frame (for example when there are multiple results in one location). Instead of scrolling in the frame, you scroll in the map, resulting in zooming in and out of the map.

On some sites it does work, for example on maand van de geschiedenis (http://amsterdam4en5mei.ginger-test.driebit.net/nl/search?qs=waterloo#eyJxcyI6ImFtc3RlcmRhbSIsInR5cGUiOiJtYXAiLCJ5ZWFyU2VsZWN0ZWQiOiIyMDE2IiwiZGF0ZV9zdGFydF95ZWFyIjoyMDE2LCJjYXQiOltdLCJrZXl3b3JkIjpbXX0=)
But on most it doesn't, for example on Nieuwwest Express (http://nieuwwestexpress.ginger-test.driebit.net/nl/search?qs=west#eyJxcyI6Indlc3QiLCJ0eXBlIjoibWFwIn0=) and Geheugen van Oost (http://geheugenvanoost.ginger-test.driebit.net/en/search?qs=oost#eyJxcyI6Im9vc3QiLCJ0eXBlIjoibWFwIn0=)

**Comment by DorienD** [comment]
@lvandergrient could you take a look at this?

**Comment by lvandergrient** [comment]
This works as designed. The default behaviour of a map in the search results is to zoom on scroll. amsterdam4en5mei has a customised search results template that does not enable zooming.
