### ISSUE TITLE
Thumbnails go over page titles/categories in frontend and backend

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#175]
Thumbnails go over page titles/categories in frontend and backend in edit mode. See screenshots taken from tudelft.openresearch.net and joodsmonument.nl. Seems to happen when there is a thumbnail + long(er) title and on narrow screens.

![edit__ied_2016_research_projects](https://cloud.githubusercontent.com/assets/20204550/18309229/955702f2-74f8-11e6-9353-f9d197695040.png)

![bewerk__ ellemarie_bolomey_-_de_zwart _ _joods_monument_admin](https://cloud.githubusercontent.com/assets/20204550/18309444/bb95a92c-74f9-11e6-810f-5529f45e5b71.png)

**Comment by mworrell** [comment]
Fixed in Zotonic (will be part of Zotonic 0.25)
