### ISSUE TITLE
Users aren't allowed to add a title or subtitle or upload an image/change content group

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#177]
When users want to make a contribution to a war victim on joodsmonument.acceptatie (a story or an image), they aren't allowed to add an image, or to provide a title or subtitle (the fields are grey and the cursor changes to a forbidden sign when mousing over). 
It unfortunately does not happen consistent so it's really hard to reproduce, but Dorien and Dirk have seen it happen too.

In addition to this, users are not allowed to change the content group setting (contribution visible to users without account/only visible to users with an account), the contribution can only be saved as 'all visitors of the monument'. For the other setting, Ginger says 'sorry, something went wrong'.
This does happen consistently on joodsmonument.acceptatie.

**Comment by Dirklectisch** [comment]
I am really trying hard to reproduce this but I just don't seem to be able to on my computer.

**Comment by ddeboer** [comment]
@Dirklectisch And on acc?

**Comment by ddeboer** [comment]
@DorienD Can you give this one a try? If you find no problems either, we’re going to close this one.

**Comment by DorienD** [comment]
I can also not reproduce this anymore, this was a problem both @krista-ramakers and i had it yesterday. But lets reopen when it happens again.
