### ISSUE TITLE
Announcements banner

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#180]
### Proposal

A banner for announcements that can be edited in Ginger. Use cases:
- maintenance/disruption announcements
- availability announcements (e.g. during holidays)
- anything else
### Plan
1. Create an unpublished rsc `site_banner` in the fixtures.
2. When published, show the banner with some kick-ass CSS.

**Comment by Stephanvdmeer** [comment]
options:
- homepage take-over. 
- all site take-over.

**Comment by DorienD** [comment]
We can close this issue right? Since its a duplicate of #214

**Comment by ddeboer** [comment]
Yup!
