### ISSUE TITLE
Do not rely on temporary_rsc

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#183]
We now use the [temporary_rsc](http://zotonic.com/docs/0.x/ref/filters/filter_temporary_rsc.html) filter in mod_ginger_remark. A temporary remark rsc is created any time the remark form is _shown_. Two problems:
- It seems silly to me to do this before any user interaction happened (e.g. submitting the form) that would require persisting a resource, let alone a temporary resource.
- Although only one temp resource is created per session, the admin interface is spammed with such resources when many users are active on the website.

**Comment by Dirklectisch** [comment]
This hasn't been a huge problem so far since most sites don't auto show the remark form. The reason that we had to use temporary resources in the first place is because the editor is able to connect media before submitting the contents of the remark. We use the default Zotonic dialogs for that and those require a subject id. See for example:

https://github.com/driebit/ginger/blob/master/modules/mod_ginger_remark/templates/remark/remark-edit.tpl#L48
 
There is no easy way around that for now unless we overhaul how those dialogs work. The connections could then be made after the resource form is posted but to do that we will have to remember somewhere to do that later on. I'm unsure what would be a straight forward way to do that. Any suggestions @ddeboer ?

One not super elegant way, would be to insert more subjet|depiction fields into the form using javascript after creating the media resources.

https://github.com/driebit/ginger/blob/master/modules/mod_ginger_remark/templates/remark/remark-edit.tpl#L6

**Comment by ddeboer** [comment]
>  to do that we will have to remember somewhere to do that later on. I'm unsure what would be a straight forward way to do that. Any suggestions @ddeboer ?

One way is to:

1. store a queue of edges in a user session property 
2. check that session property each time a resource is persisted
3. try to insert the queued edges (perhaps selected by subject id).

However, a simpler way is probably to *hide* the temporary resources from the admin. I’ll try this first.

**Comment by mworrell** [comment]
The real problem seems to me creating a temporary resource on a common page.  The purpose for the temporary resource is when there is a conscious decision for creating a new page.

**Comment by fredpook** [comment]
The "conscious decision for creating a new page" (with a temporary rsc id) was a UI for opening a dropdown with the form fields (the richtext editor with the "add media" UI). There maybe quit a few curious visitors that open that UI resulting in many empty temporary rsc's but they will be automatically cleaned after a while.

**Comment by mworrell** [comment]
In that case (of the needed user interaction), I guess this is not a big problem at the moment.

**Comment by ddeboer** [comment]
For some clients (Hart) we show the remark form right away, which immediately triggers the creation of a temporary resource. 

I don’t think there is a way to delay the creation until the user clicks in the editor to add some edge (e.g. a media item). Or is there?

**Comment by fredpook** [comment]
@DorienD why has the remarks UI changed in "Hart"? We can't have a form that triggers a temporary rsc on each page view!
@mworrell is there a notification at the "add media" UI in the richtext editor in zotonic?

**Comment by ddeboer** [comment]
@fredpook The client wants to see the form right away, without having to click on a ‘Add your reaction’ link.

**Comment by mworrell** [comment]
If the form has to be shown right away, then it can not use the temporary resource solution.

**Comment by ddeboer** [comment]
Thanks for the clear feedback, @mworrell. 

While I’ll try to get this client to accept our not showing the form right away, it seems silly that we cannot offer the option where the form is shown *without* clicking on some link/button first. :wink:

So we’re back at this issue’s title ‘Do not rely on temporary_rsc’. @Dirklectisch @fredpook Can we come up with a solution for the remarks without relying on temporary resources?

**Comment by mworrell** [comment]
Of course a re-thinking of that whole form should be possible. Don't forget that the temporary resource was really meant for more complicated editing (think of attaching images, etc) in an editorial interface.

**Comment by ddeboer** [comment]
Right, the only thing that we do in the remark form is adding media (so creating depiction edges).

**Comment by mworrell** [comment]
One way out can be some re-design where you request a resource id in a *just-in-time* manner.  Not too hard, just that the current routines are not designed to be used in that way.

**Comment by mworrell** [comment]
@ddeboer so it is really a *story about*, not a comment...

**Comment by ddeboer** [comment]
@mworrell Exactly: (what has here [been called](https://github.com/driebit/ginger/tree/master/modules/mod_ginger_remark) a) remark  – about –  some page.

**Comment by fredpook** [comment]
Yes the working title was "mini story" and was later renamed "remark"

@mworrell  if there is a notification at the "add media" UI in the richtext editor, we would could do a re-design but it is not very urgent right now.

**Comment by mworrell** [comment]
It is quite a bit of work to get this right, so let's delay to when it is needed.

**Comment by mworrell** [comment]
BTW I find that "remark" does not cover the use cases for this functionality. A "remark" is some casual statement, not a complete story with media.

http://www.dictionary.com/browse/remark?s=t

**Comment by ddeboer** [comment]
> I find that "remark" does not cover the use cases for this functionality.

Couldn’t agree more. Let’s just say we’ve already had some discussion about the naming here. :wink:

**Comment by Dirklectisch** [comment]
@Devenwel Would it be possible to re-initialize the editing interface once you start interacting with it? Just show a basic form (with a text field) at first, and then when someone is actually using it init the full blown interface that uses the temp resources?

**Comment by ddeboer** [comment]
@Dirklectisch Good idea! Perhaps a simple JS event handler with a wired action is sufficient.

**Comment by Devenwel** [comment]
@Dirklectisch my first thought was to trigger a wire on click of the 'add media' button, which creates the new resource on the backend and returns the new ID. But this would probably open up a whole new can of worms.

**Comment by ddeboer** [comment]
@Devenwel Have you tried it? Perhaps it just works. :wink:

**Comment by mworrell** [comment]
My first thought was:  show an empty textarea, on focus mask it and load the whole edit interface.  So you have an "inviting" textarea (as the client requested) but not the overhead of loading tinymce and the temporary resource on normal page views.  (Only 1 in *many* do leave a comment anyway)

**Comment by fredpook** [comment]
Nice idea, The tinymce edit buttons appearing when you click on the textarea.

**Comment by DorienD** [comment]
Whats the status of this issue? @Devenwel @fredpook
