### ISSUE TITLE
Names of models and tables

### ISSUE THREAD

**Issue by mworrell** [driebit/ginger#184]
In https://github.com/driebit/ginger/blob/master/modules/mod_ginger_activity/ there is a model m_activity.erl

https://github.com/driebit/ginger/blob/master/modules/mod_ginger_activity/models/m_activity.erl

Please rename to something that includes the name of the module. Models without module prefix can be claimed by Zotonic core (where we definitely will be adding activity logs).

In this case it would `m_ginger_activity` and the table should be `ginger_activity_log`.

**Comment by mworrell** [comment]
BTW view counting is something that you definitely *don't* want to log in the database. What are you doing if you have 10K views per second?

**Comment by fredpook** [comment]
@Dirklectisch can you look into the statistics possibilities of zotonic?

**Comment by ddeboer** [comment]
Also added to [our guidelines](https://github.com/driebit/ginger/blob/master/docs/guidelines.md#14-prefix-model-and-table-names-with-ginger) for future reference.

**Comment by ddeboer** [comment]
@mworrell Do the statistics include a page view counter?

**Comment by mworrell** [comment]
No, because we didn't have any use for it yet.
And it is quite a project to do it right (or good enough).

It is something that would be nice though, also as a (basic) replacement of Google Analytics.

**Comment by ddeboer** [comment]
Yep, we would need some write behind strategy. @mworrell Let’s do this in Zotonic?

**Comment by Dirklectisch** [comment]
To be clear, none of our sites have 10k views per second and this approach was chose due to time constraints.

**Comment by ddeboer** [comment]
@Dirklectisch Please rename the activity model so we can close this issue.

**Comment by ddeboer** [comment]
🍻

**Comment by Dirklectisch** [comment]
@DorienD Don't forget to rename calls in templates to this model upon next release.
