### ISSUE TITLE
Log to Logstash/Elasticsearch

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#188]
- See https://github.com/zotonic/zotonic/issues/992 and [mod_logging_elastic](https://github.com/zotonic/mod_logging_elastic).
- Use a standard log format.

**Comment by Dirklectisch** [comment]
Apparently [mod_logging_elastic](https://github.com/zotonic/mod_logging_elastic) already handles posting Zotonic log messages to Elastic quite well. It does however not use Logstash as an intermediate for processing the logs. I wonder if that is really needed though. Maybe @CyBeRoni could weigh in on that?

By default [mod_logging_elastic](https://github.com/zotonic/mod_logging_elastic) keeps one index per site, we might want to partition that in other ways? Does Elastic support queries over multiple indexes? One of the possible pitfalls of partitioning the data by time is that we might lose the ability to query over any arbitrary time period. If we are going to stick with an index per site, we will need to think about pruning old data if the index ever gets too large.

Furthermore there is a ton of opportunity to further enrich the logging information. There are many sources of information available at the moment of logging. For example we could show the page_id or url if we were handling a request. Just think about how this would enhance your debugging capability! Suggestions for info you would like are welcome below.

**Comment by ddeboer** [comment]
> Does Elastic support queries over multiple indexes?

Yes: queries and therefore also aggregations. 

It is [recommended](https://www.elastic.co/guide/en/elasticsearch/guide/current/retiring-data.html), however, to have time based indexes. 

We should do both: partition per site and
per day. If we decide not to use Logstash we can add this functionality to mod_logging_elastic.

**Comment by Dirklectisch** [comment]
In that case I'm also in favour of partitioning by site and day for the Zotonic error logs. It sounds like that will simplify cleaning up old data considerably. 

We can either modify the mod_logging_elastic to do that, or leverage that module's formatting and send it to logstash. The latter might give us a more uniform approach to logging that we can also leverage for other types of logs.

**Comment by Dirklectisch** [comment]
I discussed this further yesterday with @CyBeRoni and he thinks there is still value in using Logstash as an intermediate. Shall I just make an new module that builds on top of mod_logging_elastic but sends the logs over UDP using syslog?

**Comment by Dirklectisch** [comment]
I made some progress on this, there is now a Logstash branch that contains a working Logstash configuration for docker. Logging stuff from the erlang shell works, but somehow logging from a pid_observe doesn't. Also: while both the erlang library for syslog as well as the logstash claim to follow the RFC parsing the messages doesn't seem to work correctly out of the box. I'll try to put in some more time this week.

**Comment by ddeboer** [comment]
Feel free to open a WIP PR.

**Comment by ddeboer** [comment]
Logstash now processes the log messages we send from dev and ginger-test. I’ll continue working on adapting the Logstash config so that severity levels etc. are processed correctly: currently all log messages have level 0.

**Comment by ddeboer** [comment]
Fixed by tweaking the Logstash config.
