### ISSUE TITLE
Tweaking the preview of the Ginger embedded pages

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#189]
Can we tweak the preview of embedded Ginger pages? It looks a little coarse right now to @eminetuzkapan's, @kathleenvw's and my opinion. :-) I added a screenshot of a Ginger page embedded in a Wordpress site.

Maybe starting by just reducing the font size of 'source: [URL]' a little, and not underline everything? 
Ideally it might look something like the preview of Ginger pages on Twitter, as we see it here: https://twitter.com/AmsterdamMuseum/status/778609898019880961.

![voorbeeld embed event](https://cloud.githubusercontent.com/assets/20204550/18749118/a68e000a-80d5-11e6-9f99-f63fb9fcfa73.png)

**Comment by ddeboer** [comment]
Looks a bit better [here](https://hartamsterdam.ginger-acceptatie.driebit.net/nl/page/50940) but there’s still room for improvement.

**Comment by krista-ramakers** [comment]
I doubt if it has to be shortened, but maybe it can be made a little more visually attractive, with a more prominent place for the image? 

Another thing I noticed when we share a page with a Ginger embed in Slack for example, the preview displays as if it is a video. Is fixing that something that also belongs in this issue?

![slack](https://cloud.githubusercontent.com/assets/20204550/18778029/9eeafa72-8172-11e6-8fff-e8a50cb0158b.png)

**Comment by DorienD** [comment]
ping @krista-ramakers , make a new issue of the share img

**Comment by krista-ramakers** [comment]
Done @DorienD, I will close this issue since the preview looks much better now :)
