### ISSUE TITLE
High resolution masthead banner should not be cropped

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#191]
High resolution banners seem to be cropped by default, and because of the cropping, the image does not show in high res anymore. 
Found out about this at tudelft.openresearch.net and reproduced here: https://mijnzuiderzee.ginger-acceptatie.driebit.net/page/6579/test-zoekopdracht (the image I uploaded is 2900 x 700 px).

**Comment by ddeboer** [comment]
What’s the original image’s extension?

**Comment by krista-ramakers** [comment]
It's a .jpg image.

**Comment by fredpook** [comment]
@DorienD in masthead.tpl and masthead mediaclass is a crop parameter, scaling would work better, I think. Can you check why there is cropping of the banner in Ginger?

In surf I removed the cropping and the result looks like this:
https://tudelft.openresearch.net/page/19078/what-to-do-with-big-data

**Comment by ddeboer** [comment]
@gunnar-driebit Can you look into this?

**Comment by gunnar-driebit** [comment]
I made a fix in the 191-masthead-image-resolution branch.

**Comment by ddeboer** [comment]
@gunnar-driebit Just create the merge request referencing this issue. GitHub will automatically show it here.

**Comment by DorienD** [comment]
Is this fixed?
