### ISSUE TITLE
Opening documents in IE/Edge

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#201]
When opening a document in IE or Edge instead of starting a download or opening a new tab with the document, an empty page opens. 

For example:
https://tudelft.openresearch.net/page/17822/spg-full-report-rotterdam-2
Open the document on the bottom of the page

or

https://www.planidoo.be/mijn-projecten/5110/test234/promotie/promotieplan
Log in on Planidoo
Open a project
Go to 'promotie'
Go to 'Promotieplan opmaken'
Try to open the document

**Comment by fredpook** [comment]
fixed in https://github.com/driebit/ginger/commit/94e251d3525c2867e25f8803d99f51828ce4cd18
in master, will be deployed in next release.

On tudelft its already online.
For planidoo please make a issue on the planidoo gitlab
