### ISSUE TITLE
ACL rule not updated but added when already present

### ISSUE THREAD

**Issue by row-b** [driebit/ginger#202]
When an ACL rule is added through manage_schema() with the ginger_acl:ensure_acl_rule() function it is added, not updated if present. This results in multiple identical acl rules. It looks like  this only happens when the content_group_id parameter is used.

Example:
```erlang
   ginger_acl:ensure_acl_rule(
        [
            {acl_user_group_id, m_rsc:rid(user_group_project1, Context)},
            {content_group_id, m_rsc:rid(content_group_project1, Context)},
            {is_owner, true},
            {actions, [view,insert,update,link]},
            {category_id, m_rsc:rid(contribution, Context)}
        ],
        Context
    ),
```

**Comment by ddeboer** [comment]
`ginger_aclensure_acl_rule/2` should no longer be used. Use [managed rules](http://docs.zotonic.com/en/latest/ref/modules/mod_acl_user_groups.html#managed-rules) instead.

**Comment by row-b** [comment]
Yep, with managed rules it work as promised.
