### ISSUE TITLE
Validate every field that can contain an URL

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#203]
Users can add their website/Facebook/Linkedin/Twitter URL to their profile page for example. 

It would be very nice to have every field that can contain a URL, validated by Ginger. Wrongly provided URL's can cause a lot of 4[XX] errors, because URL's like these are generated: http://www.maandvandegeschiedenis.nl/page/3686/www.facebook.com/openluchtmuseum 

These 4[XX] errors are not very user friendly plus they have a negative influence on website's rankings in search engines, so it would be nice to prevent this from happening in the future. :)

**Comment by fredpook** [comment]
There is a html5 input type "url" that makes sure http:// is used. You can test it on maandvandegeschiedenis/acceptatie if that works ok I can put it in ginger edit as well

**Comment by ddeboer** [comment]
The HTML input offers only client-side, and therefore not fully reliable validation, so we need a [validator](http://docs.zotonic.com/en/latest/developer-guide/forms-and-validation.html) in Zotonic. 

Additionally, we may want filtering: if the user enters `bla.com`, prefix that automatically with `https://bla.com`.

**Comment by krista-ramakers** [comment]
Yeah it would be nice to prefill 'http(s)://' because 'Please enter a URL.' might be a little abstract for users of the sites, who might consider URL's starting with 'www' to be valid enough. 

I quickly checked it on Maand on acceptatie, and they have a lot of profile editing options (so it's a very long page). If you click 'save' at the top of the page, and the URL's aren't valid, it's not really clear why it won't save. You have to scroll down again to see what's up. So a notification indicating one (or multiple URL's) aren't valid, would definitely nice to have too.

**Comment by fredpook** [comment]
Ok, so we html validation doesn't work for us and we need to write a zotonic validator ...

**Comment by krista-ramakers** [comment]
In addition to this: there is a validator which checks the input when you want to create an external hyperlink. It validates when the input starts with 'www' (by asking if you'd like to add 'http://') but if you were to type 'driebit.nl' for example, it doesn't ask if you'd like to add 'http://'.
