### ISSUE TITLE
IE11: cursor in search bar is aligned in the middle, until you start typing

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#204]
Cursor in search bar is aligned in the middle, until you start typing the search information (see screenshots).
![maand_search_midden](https://cloud.githubusercontent.com/assets/20204550/19729604/e30522e8-9b97-11e6-89af-8f1dffba5408.jpg)
![maand_search_links](https://cloud.githubusercontent.com/assets/20204550/19729605/e30634d0-9b97-11e6-8a61-0e4b4d4d5e5b.png)

**Comment by kathleenvw** [comment]
https://github.com/driebit/ginger/issues/60, related?
