### ISSUE TITLE
Think of a way to enable admins/site editors to control their redirects 

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#206]
Admins/site editors have a few ways to create redirects, for example by checking the tick box 'Redirect to website on page view' and by editing the page path in the 'advanced' block in Ginger edit mode. 

Creating these redirects with these features causes search engine crawlers to consider them als 302's; temporary redirects. Because of this, these crawlers do not pass link equity to other pages, which has a negative influence on search engine ranking (which could mean less visitors on the website).

Can we think of a way to enable admins/site editors (if applicable) to control the kind of redirects they create? So that they can choose whether they make a permanent or temporary redirect?

**Comment by ddeboer** [comment]
Will your regular editor actually understand the difference between the two?

**Comment by krista-ramakers** [comment]
If we explain to them why it's important, yes. 
We can also choose to only enable admins to do this and offer up the help of our s&s team members if need be, since we offer to take the improvements out of their hands anyway.
