### ISSUE TITLE
TinyMCE media dialog does not handle "upload" as initial tab

### ISSUE THREAD

**Issue by fredpook** [driebit/ginger#207]
Module remark has tabs_enabled=["upload","oembed"] and initial tab="upload" but the initial tab "upload" does not display when the dialog is opened from TinyMCE

**Comment by fredpook** [comment]
@ddeboer maybe this issue is better moved to zotonic and the fix could be this diff

[zmedia_upload_dialog.txt](https://github.com/driebit/ginger/files/555830/zmedia_upload_dialog.txt)

I don't see why the initial tab for zmedia should be restricted in zotonic

**Comment by ddeboer** [comment]
@fredpook Please open up a PR at Zotonic with your proposed changes so we can review them.

**Comment by fredpook** [comment]
OK, https://github.com/zotonic/zotonic/pull/1497

**Comment by ddeboer** [comment]
Part of Zotonic 0.23.0.
