### ISSUE TITLE
Make mod_multi_upload suitable for users without admin rights

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#209]
We would like to use mod_multi_upload for some of our websites and I tested it, but it needs a little adjustment before we can activate it on live. There are two buttons front end that redirect to the admin log on screen, which doesn't really add to the (regular) user's convenience.

The 'advanced upload' button redirects to the admin log on screen.
The 'edit' button redirects to admin log on screen.
(I marked them both in the added screenshot)

![edit__met_article](https://cloud.githubusercontent.com/assets/20204550/19812635/adb298a0-9d36-11e6-9d1f-50f1577fe3ab.png)

**Comment by DorienD** [comment]
I've removed the edit button
