### ISSUE TITLE
editable 404 page

### ISSUE THREAD

**Issue by Stephanvdmeer** [driebit/ginger#212]
Would be nice to have the option to edit your 404. Clients can make there own 404 page with blocks (text, media etc).

**Comment by DorienD** [comment]
Made a branch for this, https://github.com/driebit/ginger/tree/404. @ddeboer if i'm not finished with this can i already make a pull request? So we can discuss this issue there? How does that normally work?

**Comment by ddeboer** [comment]
Exactly like you’re proposing: create a PR from the branch, and name it `[WIP] bliblabliep` so we know it’s still a WIP (work in progress).

**Comment by DorienD** [comment]
See https://github.com/driebit/ginger/pull/221 for progress on this issue
