### ISSUE TITLE
Warning bar in acceptance environment

### ISSUE THREAD

**Issue by Stephanvdmeer** [driebit/ginger#214]
It happens sometimes that clients are using the acceptance environment when thinking that they are at production/live.  To prevent mistakes it would be good to see a clear warning in Ginger (YOU ARE WORKING IN ACCEPTANCE). Is it possible to have a standard warning bar (like a cookie bar) in all sites that reminds you of this. (maybe even possible at the frontend of the site too).

**Comment by DorienD** [comment]
Very good idea! I will make this in Ginger base.

**Comment by Dirklectisch** [comment]
Another option would be to change the color of the admin menu bar for non-production environments.

**Comment by Stephanvdmeer** [comment]
@Dirklectisch is that clear enough, I think clients don't see the difference between a green, red of orange menu? I was thinking about a bar at the top or bottom of the page that can be clicked away.

**Comment by ddeboer** [comment]
We should also think about based on what condition we want to show the warning: 

- setting in the site config?
- current hostname?
- something else?

**Comment by Dirklectisch** [comment]
It should probably be a global config key for the whole server instead of a per site config. Maybe something in the zotonic.config?

**Comment by DorienD** [comment]
I would also like it to be an global config key, so you also can't 'forget' to switch it on.

**Comment by DorienD** [comment]
Is it possible to make this a global setting @ddeboer @CyBeRoni

**Comment by ddeboer** [comment]
Sure. Just use `m.config` for now (see [docs](http://docs.zotonic.com/en/latest/ref/models/model_site.html). That way, you can just add a *site* config param (also on dev) to test the warning. Using Puppet, we’ll propagate the param to all sites on acceptance (just like I did for seo_noindex).

**Comment by DorienD** [comment]
Ah ok! Cool, i will make a pr for this

**Comment by DorienD** [comment]
@ddeboer @Dirklectisch @CyBeRoni  I've discussed this with Danny, and we think it would be best if we make a module for this. Since there are still websites on our servers that are not connected to ginger base. And the bar should always be available even if you don't use the ginger base or foundation. In the mod_ginger_env(? or mod_ginger_warning) we would add a _html_head.tpl with a javascript file inside it that appends the warning to the body. This warning can be closed and a cookie will remember the close action for a period of time. What do you think?

**Comment by CyBeRoni** [comment]
Make it generic so you can specify the message in the configuration file? Then you can use the same module for any kind of warning to be added for whatever reason.

**Comment by ddeboer** [comment]
Yeah, what about a `mod_ginger_banner`? The text (and maybe status, such as ‘warning’ or ‘info’) could come from a resource. The banner is then shown:

- if a `show_banner` param in the site database or site config file is enabled (using `m.config`)
- or if the `banner` resource is published; useful if customers want to display some site banner on production.

**Comment by DorienD** [comment]
Allright! I'm on it! Would the show_banner overrule the banner rsc?

**Comment by CyBeRoni** [comment]
Wouldn't be unreasonable to allow for more than one banner, no?

"Warning: this is acceptatie"
"Please be advised the content will be copied tomorrow kthxbai"

**Comment by DorienD** [comment]
See https://github.com/driebit/ginger/pull/222

**Comment by DorienD** [comment]
![screen shot 2016-11-11 at 18 10 20](https://cloud.githubusercontent.com/assets/5102362/20223477/2c5fa3d8-a83a-11e6-817f-3e299e2f9995.png)

Works!

**Comment by DorienD** [comment]
If you've used the banner rsc, it takes the body text so editors can add links in them.

**Comment by DorienD** [comment]
Should we add a config value for the message text we want to be able to control? Like the staging text? something like `banner_message`

**Comment by CyBeRoni** [comment]
Yes.

**Comment by DorienD** [comment]
@casperglorius can you look at this with your design skills? I've made it now that its standard the $mainThemeColor of the site or Ginger Orange when you're not working with ginger foundation.
