### ISSUE TITLE
Copying text with links into the body text 

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#215]
When i try to copy some text hat had links in it into the body text I can't save the item. This happens on acceptatie and test (not on live pages).

For example:
Try to copy text from https://mediaweb.nl/blog/seo-trends-2017?utm_medium=email&utm_campaign=Dit+worden+de+SEO+Trends+voor+2017&utm_source=Blog or https://www.britannica.com/biography/Napoleon-I into the body text of a random item (text, collection etc.)
Try to save
See error "something went wrong. sorry."

I see this behavior on all browsers.

When copying to match style you can save (but then obviously the links are gone) and copying text from wikipedia does seem to work.

**Comment by fredpook** [comment]
I tested copy/paste some of that text here:
http://nieuwwestexpress.ginger-test.driebit.net/nl/page/16671/seo-trends
and seems to work.
@kathleenvw  how much did you try to copy? The whole page?

**Comment by kathleenvw** [comment]
No, just a small part. I tried it on MijnZuiderzee, MaandvandeGeschiedenis and Nieuwsbegrip, among others: https://mijnzuiderzee.ginger-acceptatie.driebit.net/admin/edit/6591, https://maandvandegeschiedenis.ginger-acceptatie.driebit.net/admin/edit/1429 and on http://nieuwsbegripnl.ginger-test.driebit.net/admin/edit/394

I see that it does work on NieuwWest Express.

**Comment by fredpook** [comment]
Ok, but each one you tested with the same small part?
Can you test with parts untill you get the error and then look into the source code <> button to figure out what bit of code caused the error? :)

**Comment by kathleenvw** [comment]
I used different parts of different texts/sites, but I now see this is a Zotonic issue. So I will move it to the Zotonic Github.
![bewerken_ test _ _maand_van_de_geschiedenis_admin](https://cloud.githubusercontent.com/assets/19573451/20064905/8c7d0f0c-a50c-11e6-9003-0e86665c7d9e.png)

**Comment by fredpook** [comment]
It is an zotonic issue but before you add an issue there you have to figure out exactly what bit of code causes the error
