### ISSUE TITLE
Results on query pages when you don't have rights to see some items

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#218]
When you do a query the is_visible check is done afterwards. When you don't have the rights to see al the items you get unexpected results. 
For example: you see two results and a button 'see more'. When clicking the button the are six more results. It is strange that you don't see these from the beginning.

**Comment by Dirklectisch** [comment]
Yup

**Comment by DorienD** [comment]
@Dirklectisch Is this something we can check in the ginger_search if an item is visible?

**Comment by Dirklectisch** [comment]
@DorienD No we can not. We can not do ACL checks for now on search results because that is a kind of expensive operation. This has been discussed several times and there is not a clear solution so far.

**Comment by ddeboer** [comment]
ACL checks at search time are limited to these three:

1. `content_group_id` the resources belong to
2. `is_published`
3. `is_unfindable`.

Other ACL checks can only happen *after* the search query, so when displaying the results.

@kathleenvw Do you have some example content? Why is it not visible? Could it be solved by moving the content to a different content group, or checking ‘not findable’ or unpublishing it?

**Comment by DorienD** [comment]
ping @kathleenvw
