### ISSUE TITLE
Ginger embed pages preview like it's a video

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#220]
I noticed when I shared a page with a Ginger embed in Slack for example, the preview displays as if it is a video. Like this screenshot:

![slack](https://cloud.githubusercontent.com/assets/20204550/20216148/493389c8-a819-11e6-9217-090f385bde4a.png)

**Comment by DorienD** [comment]
We should edit the mime type for ginger embed, so we can add a mimeicon image for this.

**Comment by DorienD** [comment]
@ddeboer what was the decision for using <ginger-embed> instead of an iframe.

**Comment by ddeboer** [comment]
https://github.com/driebit/ginger/blob/master/modules/mod_ginger_rdf/README.md#embeds
