### ISSUE TITLE
Ginger edit front end changes

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#229]
Regular uses working with the front end edit can choose to create an internal or an external link. When they choose to create an internal one, they are provided with the option to create new page, of which they can choose the content group and category. I noticed this on the Geheugen sites on production.

I think the 'create a new page' option (when creating an internal link/adding a media item) should be excluded from the front end editor by default, because this can create a lot of confusion for the regular user.
![bewerk_verhaal 2](https://cloud.githubusercontent.com/assets/20204550/20342312/34c6eeb0-abea-11e6-8983-9b39ff402656.png)

**Comment by Dirklectisch** [comment]
I would like that button to stay, the heading text for that tab is crystal clear if you ask me.

**Comment by DorienD** [comment]
@Dirklectisch why do you want to keep this button on the ginger edit? When you make a new page you also go to the edit of that page and lose the page you are editing now. This is really confusing for users.

**Comment by krista-ramakers** [comment]
Add to Dorien's argument that I don't think it is a good idea to let regular users set in which page group they publish a page. That can create confusion and maybe even 'lost' pages.

**Comment by Dirklectisch** [comment]
Sorry didn't realise this was on the front-end edit. I would like to keep it in de admin interface.

**Comment by fredpook** [comment]
We could overwrite the _editor.tpl and add a check on dispatch "ginger_edit" to set the tabs_enabled parameter.

**Comment by DorienD** [comment]
@fredpook Can you fix this? Sounds like a good solution.

**Comment by fredpook** [comment]
@krista-ramakers i also fixed this in geheugenvan
