### ISSUE TITLE
Media properties: Dutch translation middle size

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#230]
In the dutch translation of the media properties the size 'middle' translates wrong. It shows as either 'tweede naam' or 'middennaam'.

This happens on both live sites and acc/test servers. 

[bewerken_ 404__deze_pagina_bestaat_niet _ _maand_van_de_geschiedenis_admin](https://cloud.githubusercontent.com/assets/19573451/20481692/b5728608-afe8-11e6-83eb-9f0c7709c424.png)

[bewerken_ overstroming_1916 _ _mijn_zuiderzee_admin](https://cloud.githubusercontent.com/assets/19573451/20481697/c65c56d8-afe8-11e6-98ef-22f218f664df.png)

**Comment by fredpook** [comment]
Will be fixed in https://github.com/zotonic/zotonic/pull/1539
