### ISSUE TITLE
Infinite refresh loop in IE11 and Edge

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#234]
@kathleenvw and I have mentioned this before and I just experienced it again while testing Ginger 0.18/Zotonic 0.22 on staging again. 
Almost every website I checked kept refreshing when visiting home, which basically means you can't click anything before the site refreshes again. 
In some cases the home page is steady, but then your log in button (if applicable) does not work and the search page keeps refreshing.

**Comment by ddeboer** [comment]
See also https://github.com/zotonic/zotonic/issues/1276.

**Comment by ddeboer** [comment]
Duplicate of #52?

**Comment by krista-ramakers** [comment]
Doesn't seem like it, this issue occurs before you even get the change to do anything on the page (logging in or whatsoever).

**Comment by krista-ramakers** [comment]
If this helps:
It seems to happen everytime we test a Ginger release combined with a Zotonic release. Last time it happened, we managed to load the 'Network' tab in Inspect mode, and found the attached screenshot. When hovering over 'refresh', it showed 'download initiated by a user refresh (F5) of the document' or 'download initiated by an update to the 'src' attribute of an 'img' element'.
![screen_shot_2016-10-12_at_18 15 56](https://cloud.githubusercontent.com/assets/20204550/20526662/5591ae84-b0c5-11e6-8e4f-3ef94fca2955.png)

**Comment by fredpook** [comment]
On my ie11 on windows10 the refresh doesn't happen but
I get the following strange console warnings. Something with the font?
![ie11-weirdness](https://cloud.githubusercontent.com/assets/5276922/20527870/4773c2c4-b0ca-11e6-9399-c0cb38bc5e32.png)

**Comment by fredpook** [comment]
Is it only on home pages with a map? Google maps loads a large amount of bits and pieces maybe ie11 doesn't like that?

**Comment by krista-ramakers** [comment]
Nope, it also happens on (home)pages without a map.

**Comment by fredpook** [comment]
It seems to be some security issue with subdomains like ginger-acceptatie.driebit.net
It is solved when you change the settings in ie11 -> settings -> internet options -> security -> trusted sites
add https://*.driebit.net

**Comment by ddeboer** [comment]
Good find, @fredpook!

The issue then seems to have something to do with the wildcard certificate we have for `*.ginger-acceptatie.driebit.net`. Does the bug occur on production sites as well, where we have separate certificates?

**Comment by kathleenvw** [comment]
I have never seen it in production, only test and staging. 

I will add the sites on the test windows laptop and monitor if I see it again after that.

**Comment by fredpook** [comment]
Unfortunately the "trusted sites" doesn't work anymore. 
It is the websocket. When I add {% script nostream %} it is solved.
Maybe it is a websocket protocol setting on acc/test? I will ask hosting ...

**Comment by ddeboer** [comment]
@fredpook That’s not a proper fix, but only hides the problem. Please clean up any live changes on acc. Your change introduced another severe bug (e.g. in Metakids).

**Comment by fredpook** [comment]
Sorry, I should cleanup my patches :) But the reason for the patch was to allow the testing of ginger sites on  acceptatie subdomains in IE11 and Edge.

**Comment by krista-ramakers** [comment]
Can we think of a proper fix? :) Fred having cleaned up his patches causes this problem to occur again, making it virtually impossible to test a Ginger/Zotonic release properly in IE/Edge.

**Comment by krista-ramakers** [comment]
*ping* It happened again while testing Ginger 0.21/Zotonic 0.26 and makes testing on IE/Edge pretty hard.

**Comment by kathleenvw** [comment]
Ping! This is still happening. Is there a way to fix this?

**Comment by mworrell** [comment]
Can't reproduce it. Tried with IE11 on Windows 10 using browserstack.
