### ISSUE TITLE
Exclude 404 page from search results 

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#235]
In Ginger 0.18 we created the option for editors to customize their 404 page. This page turns up in the search results, which might seem a little odd to the website user. Would it be possible to exclude this page from the website search results by default?

**Comment by ddeboer** [comment]
Easiest solution: add `is_unfindable=true` to the fixtures where the 404 page is created.

**Comment by ddeboer** [comment]
And set `seo_noindex`, too.
