### ISSUE TITLE
Slick slider arrows change position with image width

### ISSUE THREAD

**Issue by fredpook** [driebit/ginger#237]
It would be a great improvement is I could just click on 1 position instead of mousing to the different arrow positions all the time. 
@Devenwel Maybe a solution is keeping the modal width the same regardless of the image width?

**Comment by DorienD** [comment]
@fredpook Can you give an example of this? Not sure where this happens?

**Comment by fredpook** [comment]
for instance https://geheugenvanoost.amsterdam/page/1076/de-honden-van-de-teslatoren
in order to scroll through the images i have to move the mouse to the arrow which changes position according to the image width. Very annoying.

**Comment by DorienD** [comment]
Ah so this is for the fancybox scrolling, check.
