### ISSUE TITLE
Favorite when not logged in: redirect to profile page 

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#238]
When you want to add an item to our favorites (ik ben fan) when you're not logged in you have to log in/register (pop-up after clicking on the favorite-button). When doing so you are redirected to your profile page, you are no longer on the page you wanted to add to your favorites. This can be annoying for users. Is there a (simple) way to change this? I think it would be better if users stayed on the page they wanted to like after logging in using that button. 

This also goed for others functions like 'volg dit verhaal'

**Comment by fredpook** [comment]
On what website?

**Comment by kathleenvw** [comment]
For example on Flevolands Geheugen (test) and Geheugen sites.

**Comment by fredpook** [comment]
fixed in: 0e53c1d45b8d4de105b0f52e795e77b8a6384459
@kathleenvw can you test on test or acc?

**Comment by kathleenvw** [comment]
This looks good.

What I forgot to mention earlier is that the click on the button 'ik ben fan' doesn't register. That means that I click on it, have to log in an then have to click on it again. I would be better, I think, to find a way to remember this click, but don't show it unless you have logged in correctly. Would this be doable?

**Comment by fredpook** [comment]
Yes, you are right. That would be more user-friendly. But it is not easy to do at the moment so I skipped that work for now since the feature is not much used.
