### ISSUE TITLE
Forgot my password mails don't arrive

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#239]
When I forgot my password I can have a mail sent with instructions to reset it. This mail doesn't arrive. 
This behavior shows on all the sites I tested on staging and live (for example Planidoo, Sharemystory, GeheugenvanOost, ReinwardtCommunity).
The mail also doesn't show up on the 'junk/trash'-folder.

**Comment by ddeboer** [comment]
Seems to work fine now. Probably due to a temporary mailserver hiccup.

**Comment by kathleenvw** [comment]
Yes, everything came floading in at once. New requests seem to process correctly.
