### ISSUE TITLE
Make lightbox for images in body text optional

### ISSUE THREAD

**Issue by DorienD** [driebit/ginger#246]

**Comment by DorienD** [comment]
@casperglorius Can you explain why you want this?

**Comment by casperglorius** [comment]
Images in a body text are ofter poor quality.
Images in a body text are often designed (cropped and placed) in such a way that they form a layout with the rest of the content around it. It feels weird to make them larger / isolate them from that context.

I think this functionality only makes sense (and is expected by users) in the context of a collection of images / carousel.

**Comment by DorienD** [comment]
So would you prefer if we make an option in the body dialog to add the fancybox?

**Comment by casperglorius** [comment]
To make it optional, but not default would be my favorite option. Yes!
