### ISSUE TITLE
Remove copyright from page

### ISSUE THREAD

**Issue by loetie** [driebit/ginger#248]
It is currently impossible to fully remove the copyright from a page after it has been selected. 
After copyright selection in de admin it is now only possible to switch between different copyright options. 

Maybe there should be a empty option?

**Comment by fredpook** [comment]
Good idea, Loetie. But what will become the default? Empty or CC? or make a config key check?

**Comment by ddeboer** [comment]
> Maybe there should be a empty option?

No. All content must be published under *some* copyright/copyleft license. Publishing content without such as license is considered bad practice. For very free use, we already have the PD and CC0 options. 

> But what will become the default? Empty or CC? or make a config key check?

Currently our (conservative) default is ‘all rights reserved’. Content can then be opened up for re-use as one likes. The default can be changed by overriding [copyrights.tpl](https://github.com/driebit/ginger/blob/master/modules/mod_ginger_base/templates/copyrights/copyrights.tpl).

Let’s make the behaviour more explicit by always selecting ‘all rights reserved’ if a page has no copyright property yet.

**Comment by vincentjacobs** [comment]
Ginger should contain default option "All rights reserved". Other variants should be implemented on a site level.
