### ISSUE TITLE
Yeoman generator for new projects

### ISSUE THREAD

**Issue by DorienD** [driebit/ginger#249]

**Comment by ddeboer** [comment]
Please note we already have a [site skeleton](https://github.com/driebit/ginger/blob/master/docs/docker.md#create-a-ginger-site).

**Comment by DorienD** [comment]
Yep, but still copy pasting for the css and template structure. So would be cool if we could add options to the yeoman generator for using foundation or not, and then generate a screen.scss that suits the project

**Comment by ddeboer** [comment]
We have switched to Makefile-based setups instead.
