### ISSUE TITLE
alternative urls (permanent redirect or not)

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#252]
Zie ook: https://github.com/zotonic/mod_alternative_uris/issues/3

Currently it is impossible to define if a redirect is permanent.
It can only be changed within the database and not the user interface.

It would be nice if this could be changed within the admin.

@loetie als volger

**Comment by krista-ramakers** [comment]
https://github.com/driebit/ginger/issues/206 :)

**Comment by ddeboer** [comment]
Closing as duplicate of #206.
