### ISSUE TITLE
Pasting video URL in 'upload by URL' field creates .htm file

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#260]
When you would like to add a Vimeo/Youtube video as a new media item using the 'add media' button, and you select the tab 'upload by URL', paste that URL in the media URL field ( and hit 'Create media item' then the Youtube/Vimeo URL you pasted gets converted to and saved as a .htm file in Ginger. Is this desired behaviour? 
And maybe we can think of way to tell those buttons apart more distinctly - when you want to embed a video into a body text 'embed URL' makes sense, but when you just want to upload a video into Ginger and connect it later, it makes less sense.

![media_ _driebit_admin](https://cloud.githubusercontent.com/assets/20204550/22594404/40661f3a-ea23-11e6-8e11-023a5aa8939e.png)

**Comment by fredpook** [comment]
@mworrell we discussed earlier to unify the whole upload media dialog, One "smart" input that figures out how to handle the different formats. Any progress on this?

**Comment by mworrell** [comment]
Regretfully no progress, didn't have time to look into it.

**Comment by mworrell** [comment]
The merge request at https://github.com/zotonic/zotonic/pull/1602 would solve this issue.
Though it is only for the 1.0-dev version of Zotonic.
