### ISSUE TITLE
Dropdown to edit menu doesn't show right

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#265]
When editing the menu of a site you can do this by clicking 'add menu item'. When there are menu-items added already you can also click the edit button on the right to add a item above or below that one. When you click that button now the dropdown shows behind the items. You can't click the options (screenshot)
![bewerken_ main_menu _ _mijn_zuiderzee_admin](https://cloud.githubusercontent.com/assets/19573451/23362734/7a81b954-fcf7-11e6-9b34-dbfa3d705865.png)
This also results in the fact that you can't delete menu-items from the list. 

This happens on live as well as staging.

**Comment by ddeboer** [comment]
Already fixed in Zotonic 0.x.
