### ISSUE TITLE
Discuss and decide validation on date picker 

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#272]
I know it's a Zotonic issue, but I created this one as well to make sure we don't lose sight of it and that we're going to fix it. :)
Related to:
https://github.com/zotonic/zotonic/issues/1536
https://github.com/zotonic/zotonic/issues/920

Issues our users have with the validation (in Mantis):
#26009 and #26157.

**Comment by Dirklectisch** [comment]
It's not just the date fields either. We would also like to have a proper validation method for non form field input without resorting to very dirty hacks.

**Comment by rl-king** [comment]
A temporary solution for client side 'presence' validation of a field can be done by simply adding the 'required' attribute to the desired input field.
