### ISSUE TITLE
Optimize page speed

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#273]
Loetie and I just noticed that the pagespeed/loading times for our Ginger sites are relatively high - especially the homepages we checked - have a loading time of 4+ seconds (where a loading time of 1,5 is the most ideal), and at first sight it's hard to determine what causes this. 

Long loading times discourage the user and are also bad for search engine rankings, so if we could look into this on short term, that would be very nice.

**Comment by Dirklectisch** [comment]
We have discussed this internally before and have a hunch this might have to do with dynamic queries that are not cached on those pages. It won't be easy to fix globally though, we will probably have to profile the pages on a case by case basis and see where the performance problems occur.

**Comment by fredpook** [comment]
Another issue in page load speed is:
Render-blocking JavaScript and CSS in above-the-fold content

Google analytics says:
"Your page has 3 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources"
