### ISSUE TITLE
Changing map translation when changing site language 

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#322]
Is it possible to change the map translation when you change the site language. What happens now is when I visit a ginger site and change the language to english I still see the map in Dutch (so with Duitsland, Frankrijk etc instead of Germany and France).

**Comment by rl-king** [comment]
This is possible. We can set the preferred language when loading the map on the page.

More information can be found [here](https://developers.google.com/maps/documentation/javascript/localization)

**Comment by kathleenvw** [comment]
And this can then change depending on the preference of the user, so that one user will use the site in Dutch and will see the Dutch map and another will use it in English and will see the English map? Or is it that the default language is the same for all users?

**Comment by rl-king** [comment]
Yes we can set the maps language to the selected site language
