### ISSUE TITLE
Ambiguous parameters for "make import-db-file" command

### ISSUE THREAD

**Issue by rl-king** [driebit/ginger#323]
Currently the `make import-db-file` command takes `(db=site-name file=site-dump.sql)`.

I think we should change this to `(site=site-name file=site-dump.sql)` since all other arguments that take a 'site-name' are called 'site'.

**Comment by ddeboer** [comment]
Agreed! PRs are – as always – most welcome. 😄

**Comment by ddeboer** [comment]
Fixed in #324.
