### ISSUE TITLE
[mod_elasticsearch] fallback to postgress search in the admin

### ISSUE THREAD

**Issue by fredpook** [driebit/ginger#325]
The zotonic admin should be using the actual up-to-date data for a search in the connect dialog.
That search is a fulltext search so it uses the ES index but the index is sometimes not uptodate in a dynamic site with lots of data mutations.

I think the zotonic admin should be using its zotonic data.

**Comment by ddeboer** [comment]
But without Elasticsearch users get less relevant search results in the admin. This was one of the original problems that mod_elasticsearch solves: users not being able to find their data. Bypassing Elasticsearch in the admin would reintroduce that problem.
