### ISSUE TITLE
Add livereload snippet to <head> when mod_development is enabled

### ISSUE THREAD

**Issue by rl-king** [driebit/ginger#327]
I propose adding this snippet to the `<head>` of the document in mod_ginger_base if mod_development is enabled.

This will enable livereload without a browser plugin and on devices like tablet and phones.

```
<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
```

**Comment by ddeboer** [comment]
Why not do this in Zotonic’s mod_development itself instead of mod_ginger_base? See https://github.com/zotonic/zotonic/issues/1793.

**Comment by rl-king** [comment]
Yep, that's a better solution.

**Comment by rl-king** [comment]
Any further action on this should be in the zotonic repo
