### ISSUE TITLE
Dont report if account is known when resetting password

### ISSUE THREAD

**Issue by loetie** [driebit/ginger#331]
Currently when you ask for a new password on the login page you get a error message:

"Je hebt een onbekende gebruikersnaam of e-mailadres ingevuld. Probeer het nogmaals.

We kunnen je alleen per e-mail bereiken als we het e-mail adres hebben dat is verbonden aan je account.

Om je account te achterhalen moet je je gebruikersnaam invullen, of het e-mailadres dat we van je hebben ontvangen."

It would be better to only tell users that an email has been sent if the account is known. Then nobody can tell which accounts are valid.

**Comment by ddeboer** [comment]
Solved in Zotonic.
