### ISSUE TITLE
Let search period adjust depending on the available dates in the results (mod_ginger_collection)

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#350]
When searching on sites that use mod_ginger_collection, such as erfgoedbrabant, you can also add a filter for searching in a certain period. Now you always see the earliest and latest date available for all the results, even if you make a selection. It would be nice if this period gets adjusted to the dates that are available. So if you start the search you see the earliest and latest (in this case -2000 and 2015) and when you do a specific search, for example 'Tilburg', the period adjusts to 1365 till 1960.

**Comment by kathleenvw** [comment]
Note: we have to think about items in the results that match 'tilburg' for example, but have no date.

**Comment by ddeboer** [comment]
Already supported: add `dynamic` argument to the search filter.
