### ISSUE TITLE
Wrong HTML content when adding a figure in a paragraph

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#359]
Images don't align with the text:
![uitlijnen afbeeldingen](https://user-images.githubusercontent.com/19573451/35863272-7cc453b4-0b4e-11e8-8237-531718ec057f.png)

Original issue: https://driebit.atlassian.net/browse/EB-143

**Comment by ddeboer** [comment]
@kathleenvw What exactly is the problem in the above screenshot?
