### ISSUE TITLE
Dispatch setup for SPAs

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#408]
Best solution seems to be to to create a mod_ginger_spa, which has a `page.tpl` that
* starts the SPA (elm.js),
* while still rendering all SEO and metadata headers for Google indexing and sharing URLs on social media (e.g. Twitter).

Because mod_ginger_foundation contains more specific page templates, it must be disabled. This is fine, because SPAs don’t need its templates and CSS anyway. 

With this solution, we shouldn’t have to change the dispatch rules too much, so all non-SPA URLs (such as `/admin/*`) will continue to work without trouble. Moreover, it’s easier to maintain.

/cc @rl-king @rmies

**Comment by rl-king** [comment]
I like the idea. But we're currently using site specific ports and or flags (the ones for Elm) for each Elm based site. Which means we'll be overwriting parts or the entire `page.tpl` every time, this seems inconvenient/undesirable.

I'm talking about stuff that comes after initialising the Elm app here.
https://github.com/driebit/ginger/blob/master/skel/main.tpl

**Comment by ddeboer** [comment]
Solved in #555.
