### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#53]
**Zotonic**

For Zotonic we now have a proper release plan with a new minor version every [first Monday of the month](http://zotonic.com/docs/latest/developer-guide/contributing.html#zotonic-releases). Let’s align the Ginger releases with that.

**Ginger**
1. For testing, it makes sense to combine Ginger and Zotonic testing. Zotonic has a one week stabilisation phase prior to a release. If we combine them, there’s a Ginger release every first Monday of the month, too.
2. How many more monthly Ginger releases do we need? Probably either none or a second one, so a Ginger release every two weeks.

**Comment by CyBeRoni** [comment]
> How many more monthly Ginger releases do we need?

I'd say monthly is pretty good for feature-releases. If there's a high-priority bug that needs fixing sooner, there can be patch releases for that.

**Comment by fredpook** [comment]
Once a month seems fine for now. Bigger concern is what time of the day we release.

**Comment by DorienD** [comment]
I think once a month is also fine. Would it also depend on how fast we build functionalities in projects? @ddeboer @fredpook

**Comment by ddeboer** [comment]
Ok, let’s try the monthly release. Just created a `release-0.13.0` branch, to be tagged and released next Monday together with Zotonic (0.19.0).
