### ISSUE TITLE
Create read-only, subtree splits for independently usable modules

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#55]
Goal: for each commit to driebit/ginger, update a read-only split at driebit/mod_ginger_base, driebit/mod_ginger_foundation, etc. This is step 3 in #50. I already merged the Tagger and RDF modules (that were already on GitHub) into driebit/ginger.

Options:
- https://github.com/dflydev/dflydev-git-subsplit-github-webhook
- https://github.com/ryanwinchester/subsplit-service
- [split.sh](https://speakerdeck.com/fabpot/a-monorepo-vs-manyrepos) by the Symfony team (soon to be open sourced).

The splitting can become quite heavy for large repositories that have a long commit history; split.sh seems to solve this. Can we do the splitting on Travis (`after_success`) or would we need to boot a Docker container somewhere else?

**Comment by Dirklectisch** [comment]
Shouldn't this be the other way around? Have the Ginger repo be a collection of submodules that are edited in a separate repository?

**Comment by ddeboer** [comment]
It should not. See my explanation that I’ve just added to [the docs](https://github.com/driebit/ginger/blob/master/docs/monorepo.md).

**Comment by Dirklectisch** [comment]
Fair enough.
