### ISSUE TITLE
[base] resource_exists in REST api doesn't return 404 but 500 

### ISSUE THREAD

**Issue by rl-king** [driebit/ginger#566]
Calling `/data/resources/:id` with a non existing id returns a 500 instead of 404.

https://github.com/driebit/ginger/blob/master/modules/mod_ginger_base/controllers/controller_rest_resources.erl#L60

**Comment by ddeboer** [comment]
This is caused by `controller_rest` accepting a map instead of a list for `State`. Webzmachine doesn’t handle a map argument correctly.

**Comment by rl-king** [comment]
Ah thanks, interesting. Quite a refactor to change that as well.

**Comment by rl-king** [comment]
As suggested, replacing maps with proplists in the dispatch rules fixes this issue
