### ISSUE TITLE
Callback=`` gives error

### ISSUE THREAD

**Issue by DorienD** [driebit/ginger#568]
I'm not sure since when but in ginger edit we use an action for adding depictions to a resource:
```
{% wire id=#connect
                        action={dialog_open template="_action_dialog_connect.tpl"
                            title=[_"Add:", " ", m.rsc.depiction.title|lower]
                            subject_id=id
                            edge_template="_rsc_edge_media.tpl"
                            predicate=`depiction`
                            tab=tab|default:"upload"
                            tabs_enabled=tabs_enabled|default:["upload"]
                            callback=``
                            actions=[
                                {postback postback={reload_media rsc_id=id div_id=["links-",id|make_list,"-depiction"]}
                                    delegate="controller_admin_edit"}
                            ]}
                    %}
```

As you can see the callback parameter is with backticks `callback=`` `. This now gives an error, if we change this to `callback=""` it does work. Should backticks result in an undefined? And i'm also not quite sure how to proceed with this. Since this now gives an error on the command line and the dialog won't close in the frontend edit. The depiction resource is still correctly made.

**Comment by mworrell** [comment]
The double back-tick defines an empty atom.
The callback should be a string, so please use `""`

For delegates you can use back-ticks, as those refer to module names (which are atoms).
