### ISSUE TITLE
Docker development environment

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#57]
Replace our current Vagrant/Puppet development environment with a Docker one.

**Benefits**

1. With [Docker for Mac](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) around the corner, we can ditch VirtualBox. Docker for Mac uses the xhyve hypervisor, which is much faster and memory-efficient than VirtualBox. Moreover, it’s very easy to install and start.

2. Third-party developers will get ready-to-go images instead of being dependent on the Driebit Puppet master for provisioning.

3. Xhyve brings fast file sharing and supports inotify, so we get automatic recompilation (#27).

4. We can build on the Dockerfile from the Zotonic project instead of having a configuration from scratch.

**Proposal**

* Create a lightweight Zotonic image, without PostgreSQL: zotonic/zotonic#1295.
* Add a multi-container `docker-compose.yml` to Ginger. For now: one Dockerfile for all Ginger sites together.
* Perhaps later, run each site in its own container.

**Comment by DorienD** [comment]
Oehhhh sounds good 👍

**Comment by Dirklectisch** [comment]
Want!
