### ISSUE TITLE
Overview of Ginger modules

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#58]
# I marked the modules that should be deprecated and will be removed. Did I forget any?

| module | has README | deprecated |
| --- | --- | --- |
| mod_ginger_acl |  | ✖ |
| mod_ginger_admin |  |  |
| mod_ginger_auth | ✓ |  |
| mod_ginger_base | ✓ |  |
| mod_ginger_carousel |  | ✖ |
| mod_ginger_edit | WIP @DorienD |  |
| mod_ginger_export |  | ✖ |
| mod_ginger_foundation | TODO |  |
| mod_ginger_map |  | ✖ |
| mod_ginger_message | TODO @loetie |  |
| mod_ginger_nav |  | ✖ |
| mod_ginger_oai_pmh | ✓ |  |
| mod_ginger_rdf | ✓ |  |
| mod_ginger_remark | TODO @Dirklectisch |  |
| mod_ginger_search |  | ✖ |
| mod_ginger_site |  | ✖ |
| mod_ginger_social |  | ✖ |
| mod_ginger_tagger | ✓ |  |
| mod_ginger_timeline | TODO |  |

**Comment by DorienD** [comment]
Is ginger admin deprecated? 
Mod_ginger_carousel, mod_ginger_map, mod_ginger_search, mod_ginger_site is used by some of our older sites.

**Comment by ddeboer** [comment]
> Is ginger admin deprecated? 

Oops, no, of course not. Fixed it in the table. 😉 

> Mod_ginger_carousel, mod_ginger_map, mod_ginger_search, mod_ginger_site is used by some of our older sites.

Can you create an overview of which sites still depend on that? It will help a lot if we can migrate them to the new structure (ginger_base) and clean up our Ginger modules, particularly for newcomers to Ginger.
