### ISSUE TITLE
Coloured menu bar in admin for each environment

### ISSUE THREAD

**Issue by loetie** [driebit/ginger#599]
It would be nice to have a different coloured menu bar in the admin for each environment.
It happens to often during testing that multiple environments are used and content on the wrong environment is changed.

- Development: Blue?
- Test: Red?
- Acceptance: Driebit green?
- Production: (current) Ginger orange

**Comment by DorienD** [comment]
This will be fixed in https://github.com/driebit/ginger/pull/605
