### ISSUE TITLE
On IE search bar pointer jumps

### ISSUE THREAD

**Issue by DorienD** [driebit/ginger#60]
The type pointer jumps when you open the search in the navbar from somewhere in the middle to the left. Minor bug.

**Comment by gunnar-driebit** [comment]
I tried to reproduce this, but the behaviour is the same as on other browsers in IE11, the input has the focus, so the cursor is on the left inside the input and moves along to the left to expand over the whole width of the header. I didn't see it jump.

**Comment by ddeboer** [comment]
@kathleenvw @krista-ramakers @DorienD Do you still see this bug? If not, please close this.

**Comment by kathleenvw** [comment]
I don't see this anymore, so I'll close this issue.
