### ISSUE TITLE
Ginger-edit connection dialog bug

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#63]
When you're editing a post in the front-end, you can add keywords and receivers. When doing this a pop-up opens where you can click ons a keyword or a receiver. You can also typ in words to search for keywords. When you hit enter while searching the pop-up closes and the page refreshes. 
This means everything that you editen (and didn't save) is gone. 

This happens on all browsers.

**Comment by fredpook** [comment]
The save button in ginger_edit has some obscure javascript. This form needs a clean-up.

**Comment by fredpook** [comment]
fixed in 06d2d48
