### ISSUE TITLE
m_rdf[id] crashes on undefined title

### ISSUE THREAD

**Issue by DorienD** [driebit/ginger#631]
Steps to reproduce:

1. Create resource, choose dutch and english as language
2. Add a keyword, that has only a dutch language
3. View page

Error:
`
12:58:07.779 [warning] webmachine_mochiweb:223 caught error {stop_request,500,{function_clause,[{filter_stringify,stringify_1,[{{badmap,undefined},[{maps,keys,[undefined],[]},{ginger_json_ld,merge_values,2,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/support/ginger_json_ld.erl"},{line,343}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{ginger_json_ld,triple_to_map,2,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/support/ginger_json_ld.erl"},{line,317}]},{ginger_json_ld,'-serialize_to_map/1-fun-0-',3,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/support/ginger_json_ld.erl"},{line,206}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{m_rdf,to_json_ld,2,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/models/m_rdf.erl"},{line,359}]},{template_joodsmonument__desktop___ginger_sites_joodsmonument_templates_page_user_tpl,render2,2,[]}]},{context,joodsmonument,{wm_reqdata,#Port<0.94307>,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[controller_module_error|controller_page]],[[ua_class|desktop],[ua_props,{is_user_select,true},{has_pointer,true},{is_desktop,true},{is_crawler,false},{is_wireless_device,false},{is_tablet,false},{ajax_support_javascript,true},{device_os,<<"-">>},{displayWidth,1680},{displayHeight,1050},{inputDevices,<<"-">>},{parentId,<<"generic-">>},{model,<<"browser">>},{vendor,<<"desktop">>},{id,<<"desktopDevice">>}]],[[zotonic_host|joodsmonument]],[[controller_module|controller_http_error],[http_status_code|500]],[],[],[],[],[],[],[],[],[[error_reason|{{badmap,undefined},[{maps,keys,[undefined],[]},{ginger_json_ld,merge_values,2,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/support/ginger_json_ld.erl"},{line,343}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{ginger_json_ld,triple_to_map,2,[{file,"/Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/support/ginger_json_ld.erl"},{line,317}]},{ginger_json_ld,...},...]}]],...}}},...},...}],...},...]}} (stacktrace [{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,37}]},{webmachine_mochiweb,render_error,4,[{file,"src/webmachine_mochiweb.erl"},{line,213}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,107}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}])
Recompile: /Users/loetie/Documents/checkouts/docker/ginger/modules/mod_ginger_rdf/models/m_rdf
`

**Comment by ddeboer** [comment]
Fixed in #634.
