### ISSUE TITLE
Adding a new menu-item doesn't work

### ISSUE THREAD

**Issue by kathleenvw** [driebit/ginger#66]
When editting the menu you can't directly add a new article/collection to the list. 

Steps to reproduce:
- Log in on the admin
- Go to the menu
- Click on 'add menu item'
- Click on 'create page'
- Make a collection and add a title (and click publish)
- Click 'make'

The new item doesn't show in the list of menu items. If you then again click 'add menu item' and you look at the 'find page' you do see your new menu item and you can add it. Then is does show in the list of menu items. 

This happens on test sites, as well as on live sites.

**Comment by fredpook** [comment]
This happens in all tree interfaces, right? Like Categories and Contentgroup admin.pages?

**Comment by kathleenvw** [comment]
Right.

**Comment by fredpook** [comment]
Then its a zotonic issue. You can make your first official issue here https://github.com/zotonic/zotonic/issues
something like

"When adding to the hierarchy tree  for menu/category/contentgroup a new resource doesn't show up"

**Comment by fredpook** [comment]
Moved to https://github.com/zotonic/zotonic/issues/1309
