### ISSUE TITLE
Adlib integration

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#72]
### Storage

Store a nonauthoritative resource in Zotonic that points to the Adlib resource, similarly to how [mod_ginger_rdf](https://github.com/driebit/ginger/tree/master/modules/mod_ginger_rdf) stores linked data. To improve display performance, (a selection of) resource metadata that is shown on the website can be stored alongside the nonauthoritative resource.
### Sync

As Adlib has no push capabilities, we’ll have to periodically poll Adlib for changes.
- Fetch records that were updated since a datetime: `http://test2.adlibsoft.com/api/wwwopac.ashx?database=collect.inf&search=edit.date>'2012-06-01'`
- Fetch deleted records: [getdeletedrecords](http://api.adlibsoft.com/site/api/functions/getdeletedrecords).
### Search

When polling updates from Adlib, optionally a search index (Elasticsearch) can be updated.

**Comment by DorienD** [comment]
You are working on this right? @ddeboer

**Comment by ddeboer** [comment]
This has been done with Elasticsearch as the storage backend in [mod_ginger_adlib](https://github.com/driebit/ginger/tree/master/modules/mod_ginger_adlib) and [mod_ginger_adlib_elasticsearch](https://github.com/driebit/ginger/tree/master/modules/mod_ginger_adlib_elasticsearch).
