### ISSUE TITLE
Activity feed

### ISSUE THREAD

**Issue by ddeboer** [driebit/ginger#78]
@Dirklectisch Is this mod_ginger_activity? Please elaborate. :wink:

**Comment by DorienD** [comment]
Nope, this is the activity feed of last changed or added things. Ask Emine about TU delft project.

**Comment by ddeboer** [comment]
As seen on TU Delft/Surf website.

**Comment by ddeboer** [comment]
@Dirklectisch Did you build this? Can you port it to base or a Ginger core module?

**Comment by fredpook** [comment]
On TUdelft it is just a template (static) so nothing special. Should be a "live" template with custom pubsub subscribes.

**Comment by ddeboer** [comment]
Let’s first move the activity template into base. @fredpook Can you do this?

**Comment by Dirklectisch** [comment]
@ddeboer Somehow I missed all the mentions in this topic. mod_ginger_activity is not an activity feed. Sorry. What is does do: it let's you 'activate' a resource. What an activation means is up to the developer. Why not used edges? Well we needed support for anonymous users and register some other metadata. So far I am using it on two projects. One is a voting system the other is a visualisation of visitors on a certain resource type.
